// frontend/src/app/(dashboard)/integrations/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { webhooksApi, apiKeysApi } from '@/lib/api';

const EVENTS = ['scan_completed', 'scan_failed', 'critical_finding', 'high_finding', 'scan_started'];

type Tab = 'webhooks' | 'apikeys';

export default function IntegrationsPage() {
  const [tab, setTab] = useState<Tab>('webhooks');
  const [webhooks, setWebhooks] = useState<any[]>([]);
  const [apiKeys, setApiKeys] = useState<any[]>([]);
  const [error, setError] = useState('');
  const [newKeyVal, setNewKeyVal] = useState('');

  const [wUrl, setWUrl] = useState('');
  const [wEvents, setWEvents] = useState<string[]>(['scan_completed']);
  const [wLoading, setWLoading] = useState(false);

  const [kName, setKName] = useState('');
  const [kScope, setKScope] = useState('read');
  const [kLoading, setKLoading] = useState(false);

  async function loadWebhooks() { setWebhooks(await webhooksApi.list()); }
  async function loadKeys() { setApiKeys(await apiKeysApi.list()); }

  useEffect(() => {
    Promise.all([loadWebhooks(), loadKeys()]).catch(e => setError(e.message));
  }, []);

  async function addWebhook(e: React.FormEvent) {
    e.preventDefault();
    if (!wUrl.trim()) return;
    setWLoading(true);
    try {
      await webhooksApi.create({ url: wUrl.trim(), events: wEvents });
      setWUrl('');
      await loadWebhooks();
    } catch (err: any) { setError(err.message); }
    finally { setWLoading(false); }
  }

  async function addKey(e: React.FormEvent) {
    e.preventDefault();
    if (!kName.trim()) return;
    setKLoading(true);
    try {
      const result = await apiKeysApi.create({ name: kName.trim(), scope: kScope });
      setNewKeyVal(result.key);
      setKName('');
      await loadKeys();
    } catch (err: any) { setError(err.message); }
    finally { setKLoading(false); }
  }

  function toggleEvent(ev: string) {
    setWEvents(prev => prev.includes(ev) ? prev.filter(x => x !== ev) : [...prev, ev]);
  }

  const inp = "bg-gray-900 border border-gray-700 text-white px-3 py-2 text-sm focus:border-cyan-400 focus:outline-none";

  return (
    <div className="p-6 max-w-3xl">
      <div className="mb-6">
        <h1 className="text-2xl font-bold">Integraties & API</h1>
        <p className="text-gray-400 text-sm mt-1">Webhooks, API keys en externe koppelingen</p>
      </div>

      <div className="flex border-b border-gray-700 mb-6">
        {(['webhooks', 'apikeys'] as const).map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-5 py-2.5 text-sm border-b-2 -mb-px transition-colors ${tab === t ? 'border-cyan-400 text-white' : 'border-transparent text-gray-500 hover:text-gray-300'}`}>
            {t === 'webhooks' ? 'Webhooks' : 'API Keys'}
          </button>
        ))}
      </div>

      {error && (
        <div className="text-red-400 border border-red-400 p-3 mb-4 text-sm flex justify-between">
          {error} <button onClick={() => setError('')} className="ml-2">✕</button>
        </div>
      )}

      {tab === 'webhooks' ? (
        <section>
          <form onSubmit={addWebhook} className="flex flex-col gap-3 mb-6">
            <input className={`${inp} w-full`} value={wUrl} onChange={e => setWUrl(e.target.value)} placeholder="https://hooks.example.com/..." />
            <div className="flex flex-wrap gap-3">
              {EVENTS.map(ev => (
                <label key={ev} className="flex items-center gap-1.5 text-xs text-gray-400 cursor-pointer">
                  <input type="checkbox" checked={wEvents.includes(ev)} onChange={() => toggleEvent(ev)} className="accent-cyan-400" />
                  {ev}
                </label>
              ))}
            </div>
            <button type="submit" disabled={wLoading || !wUrl.trim()}
              className="self-start bg-gray-700 border border-gray-600 text-white px-5 py-2 text-sm hover:border-cyan-400 disabled:opacity-50">
              {wLoading ? 'Aanmaken…' : '+ Webhook toevoegen'}
            </button>
          </form>

          <div className="flex flex-col gap-2">
            {webhooks.length === 0
              ? <div className="text-gray-500 text-sm py-6 text-center">Geen webhooks geconfigureerd.</div>
              : webhooks.map(wh => (
                <div key={wh.id} className="flex items-center gap-3 p-3 bg-gray-800/30 border border-gray-700 flex-wrap">
                  <span className="font-mono text-xs text-cyan-400 flex-1">{wh.url}</span>
                  <div className="flex gap-1 flex-wrap">
                    {(wh.events || []).map((ev: string) => (
                      <span key={ev} className="bg-gray-700 text-xs px-1.5 py-0.5">{ev}</span>
                    ))}
                  </div>
                  <span className={`text-xs ${wh.enabled ? 'text-green-400' : 'text-gray-500'}`}>{wh.enabled ? 'Actief' : 'Inactief'}</span>
                  <button onClick={() => webhooksApi.remove(wh.id).then(loadWebhooks)} className="text-gray-600 hover:text-red-400 text-sm">✕</button>
                </div>
              ))}
          </div>
        </section>
      ) : (
        <section>
          <form onSubmit={addKey} className="flex flex-wrap gap-3 items-end mb-6">
            <div className="flex flex-col gap-1">
              <span className="text-xs text-gray-500">Naam</span>
              <input className={`${inp} w-52`} value={kName} onChange={e => setKName(e.target.value)} placeholder="bijv. CI/CD pipeline" />
            </div>
            <div className="flex flex-col gap-1">
              <span className="text-xs text-gray-500">Scope</span>
              <select className={inp} value={kScope} onChange={e => setKScope(e.target.value)}>
                <option value="read">Read-only</option>
                <option value="scan">Scan</option>
                <option value="admin">Admin</option>
              </select>
            </div>
            <button type="submit" disabled={kLoading || !kName.trim()}
              className="bg-gray-700 border border-gray-600 text-white px-5 py-2 text-sm hover:border-cyan-400 disabled:opacity-50">
              {kLoading ? 'Aanmaken…' : '+ Aanmaken'}
            </button>
          </form>

          {newKeyVal && (
            <div className="bg-green-900/20 border border-green-500/50 p-3 mb-4 flex items-center gap-3 flex-wrap">
              <span className="text-xs text-gray-400">Nieuwe key (eenmalig zichtbaar):</span>
              <code className="text-green-400 font-mono text-xs flex-1 break-all">{newKeyVal}</code>
              <button onClick={() => navigator.clipboard.writeText(newKeyVal)}
                className="text-xs border border-green-500 text-green-400 px-2 py-0.5">Kopieer</button>
              <button onClick={() => setNewKeyVal('')} className="text-gray-500 text-sm">✕</button>
            </div>
          )}

          <div className="flex flex-col gap-2">
            {apiKeys.length === 0
              ? <div className="text-gray-500 text-sm py-6 text-center">Geen API keys aangemaakt.</div>
              : apiKeys.map(k => (
                <div key={k.id} className="flex items-center gap-3 p-3 bg-gray-800/30 border border-gray-700 flex-wrap">
                  <span className="font-semibold text-sm min-w-24">{k.name}</span>
                  <code className="font-mono text-xs text-gray-500">{k.key}</code>
                  <span className="bg-blue-900/30 border border-blue-700/50 text-blue-400 text-xs px-2 py-0.5">{k.scope}</span>
                  <span className="text-xs text-gray-600 flex-1">{k.last_used ? `Gebruikt: ${new Date(k.last_used).toLocaleDateString('nl-NL')}` : 'Nog niet gebruikt'}</span>
                  <button onClick={() => apiKeysApi.remove(k.id).then(loadKeys)} className="text-gray-600 hover:text-red-400 text-sm">✕</button>
                </div>
              ))}
          </div>
        </section>
      )}
    </div>
  );
}

// cyberpulse/frontend/src/routes/Integrations.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    getWebhooks, createWebhook, deleteWebhook,
    getApiKeys, createApiKey, deleteApiKey
  } from '../lib/api';

  let tab: 'webhooks' | 'apikeys' = 'webhooks';
  let webhooks: any[] = [];
  let apiKeys: any[] = [];
  let loadingW = true;
  let loadingK = true;
  let error = '';

  // Webhook form
  let wUrl = '';
  let wEvents: string[] = ['scan_completed'];
  let addingW = false;

  // API key form
  let kName = '';
  let kScope = 'read';
  let addingK = false;
  let newKeyVal = '';

  const AVAILABLE_EVENTS = [
    'scan_completed', 'scan_failed', 'critical_finding', 'high_finding', 'scan_started',
  ];

  onMount(async () => {
    await Promise.all([loadWebhooks(), loadKeys()]);
  });

  async function loadWebhooks() {
    loadingW = true;
    try { webhooks = await getWebhooks(); } catch (e: any) { error = e.message; } finally { loadingW = false; }
  }

  async function loadKeys() {
    loadingK = true;
    try { apiKeys = await getApiKeys(); } catch (e: any) { error = e.message; } finally { loadingK = false; }
  }

  async function addWebhook() {
    if (!wUrl.trim()) return;
    addingW = true;
    try {
      await createWebhook({ url: wUrl.trim(), events: wEvents });
      wUrl = '';
      await loadWebhooks();
    } catch (e: any) {
      error = e.message;
    } finally {
      addingW = false;
    }
  }

  async function removeWebhook(id: string) {
    await deleteWebhook(id);
    await loadWebhooks();
  }

  async function addKey() {
    if (!kName.trim()) return;
    addingK = true;
    try {
      const result = await createApiKey({ name: kName.trim(), scope: kScope });
      newKeyVal = result.key;
      kName = '';
      await loadKeys();
    } catch (e: any) {
      error = e.message;
    } finally {
      addingK = false;
    }
  }

  async function removeKey(id: string) {
    await deleteApiKey(id);
    await loadKeys();
  }

  function toggleEvent(e: string) {
    if (wEvents.includes(e)) {
      wEvents = wEvents.filter(x => x !== e);
    } else {
      wEvents = [...wEvents, e];
    }
  }
</script>

<div class="integrations-page">
  <header class="page-header">
    <h1>Integraties &amp; API</h1>
    <p class="subtitle">Webhooks, API keys en externe koppelingen</p>
  </header>

  <div class="tabs">
    <button class="tab-btn" class:active={tab === 'webhooks'} on:click={() => tab = 'webhooks'}>Webhooks</button>
    <button class="tab-btn" class:active={tab === 'apikeys'} on:click={() => tab = 'apikeys'}>API Keys</button>
  </div>

  {#if error}
    <div class="error-msg">{error} <button on:click={() => error = ''}>✕</button></div>
  {/if}

  {#if tab === 'webhooks'}
    <section class="section">
      <h2>Webhook aanmaken</h2>
      <div class="form-row">
        <input bind:value={wUrl} placeholder="https://hooks.example.com/..." class="url-input" />
        <div class="event-checkboxes">
          {#each AVAILABLE_EVENTS as ev}
            <label class="checkbox-label">
              <input type="checkbox" checked={wEvents.includes(ev)} on:change={() => toggleEvent(ev)} />
              {ev}
            </label>
          {/each}
        </div>
        <button class="btn-primary" on:click={addWebhook} disabled={addingW || !wUrl.trim()}>
          {addingW ? 'Aanmaken…' : '+ Toevoegen'}
        </button>
      </div>

      <div class="list">
        {#if loadingW}
          <div class="loading">Laden…</div>
        {:else if webhooks.length === 0}
          <div class="empty">Geen webhooks geconfigureerd.</div>
        {:else}
          {#each webhooks as wh (wh.id)}
            <div class="list-row">
              <span class="mono url">{wh.url}</span>
              <div class="events">
                {#each (wh.events ?? []) as ev}
                  <span class="event-tag">{ev}</span>
                {/each}
              </div>
              <span class="status {wh.enabled ? 'active' : 'inactive'}">{wh.enabled ? 'Actief' : 'Inactief'}</span>
              <button class="icon-btn danger" on:click={() => removeWebhook(wh.id)}>✕</button>
            </div>
          {/each}
        {/if}
      </div>
    </section>
  {:else}
    <section class="section">
      <h2>API Key aanmaken</h2>
      <div class="form-row compact">
        <input bind:value={kName} placeholder="Naam (bijv. CI/CD pipeline)" class="name-input" />
        <select bind:value={kScope}>
          <option value="read">Read-only</option>
          <option value="scan">Scan</option>
          <option value="admin">Admin</option>
        </select>
        <button class="btn-primary" on:click={addKey} disabled={addingK || !kName.trim()}>
          {addingK ? 'Aanmaken…' : '+ Aanmaken'}
        </button>
      </div>

      {#if newKeyVal}
        <div class="key-reveal">
          <span class="label">Nieuwe API key (eenmalig zichtbaar):</span>
          <span class="key-val mono">{newKeyVal}</span>
          <button on:click={() => { navigator.clipboard.writeText(newKeyVal); }}>Kopieer</button>
        </div>
      {/if}

      <div class="list">
        {#if loadingK}
          <div class="loading">Laden…</div>
        {:else if apiKeys.length === 0}
          <div class="empty">Geen API keys aangemaakt.</div>
        {:else}
          {#each apiKeys as k (k.id)}
            <div class="list-row">
              <span class="key-name">{k.name}</span>
              <span class="mono muted">{k.key}</span>
              <span class="scope-tag">{k.scope}</span>
              <span class="muted date">{k.last_used ? `Gebruikt: ${new Date(k.last_used).toLocaleDateString('nl-NL')}` : 'Nog niet gebruikt'}</span>
              <button class="icon-btn danger" on:click={() => removeKey(k.id)}>✕</button>
            </div>
          {/each}
        {/if}
      </div>
    </section>
  {/if}
</div>

<style>
  .integrations-page { padding: 2rem; max-width: 900px; }
  .page-header { margin-bottom: 1.5rem; }
  .page-header h1 { font-size: 1.5rem; font-weight: 700; margin: 0; }
  .subtitle { color: var(--text-muted, #888); font-size: 0.85rem; margin: 0.25rem 0 0; }
  .tabs { display: flex; gap: 0; border-bottom: 1px solid var(--border, #333); margin-bottom: 1.5rem; }
  .tab-btn {
    background: none; border: none; border-bottom: 2px solid transparent;
    color: var(--text-muted, #888); padding: 0.6rem 1.25rem; cursor: pointer; font-size: 0.875rem;
    margin-bottom: -1px;
  }
  .tab-btn.active { color: var(--text, #fff); border-bottom-color: var(--highlight, #0ff); }
  .section h2 { font-size: 1rem; font-weight: 600; margin: 0 0 1rem; }
  .form-row { display: flex; align-items: flex-start; gap: 0.75rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
  .form-row.compact { align-items: center; }
  .url-input, .name-input {
    background: var(--surface, #111); border: 1px solid var(--border, #333);
    color: var(--text, #fff); padding: 0.4rem 0.75rem; font-size: 0.875rem; flex: 1; min-width: 260px;
  }
  .name-input { max-width: 240px; }
  select {
    background: var(--surface, #111); border: 1px solid var(--border, #333);
    color: var(--text, #fff); padding: 0.4rem 0.75rem; font-size: 0.875rem;
  }
  .event-checkboxes { display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center; }
  .checkbox-label { display: flex; align-items: center; gap: 0.3rem; font-size: 0.8rem;
                    color: var(--text-muted, #aaa); cursor: pointer; }
  .btn-primary { background: var(--surface, #1a1a1a); border: 1px solid var(--border, #444);
                 color: var(--text, #fff); padding: 0.4rem 1rem; cursor: pointer; font-size: 0.875rem; }
  .btn-primary:hover:not(:disabled) { border-color: var(--highlight, #0ff); }
  .btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
  .list { display: flex; flex-direction: column; gap: 0.5rem; }
  .list-row { display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem 1rem;
              background: var(--surface, #111); border: 1px solid var(--border, #222); flex-wrap: wrap; }
  .mono { font-family: 'JetBrains Mono', monospace; font-size: 0.8rem; }
  .url { color: var(--highlight, #0ff); flex: 1; }
  .events { display: flex; flex-wrap: wrap; gap: 0.25rem; }
  .event-tag { background: var(--surface, #222); border: 1px solid var(--border, #333);
               padding: 0.1rem 0.4rem; font-size: 0.7rem; }
  .status.active { color: #00cc66; }
  .status.inactive { color: #888; }
  .scope-tag { background: rgba(100,149,237,.15); color: #6495ed; border: 1px solid #6495ed;
               padding: 0.15rem 0.5rem; font-size: 0.75rem; }
  .key-name { font-weight: 600; min-width: 120px; }
  .muted { color: var(--text-muted, #888); }
  .date { font-size: 0.75rem; }
  .icon-btn { background: none; border: none; cursor: pointer; color: var(--text-muted, #666); font-size: 1rem; padding: 0.2rem 0.4rem; }
  .icon-btn.danger:hover { color: #ff4444; }
  .key-reveal { background: rgba(0,200,0,.05); border: 1px solid #00cc66;
                padding: 0.75rem 1rem; margin-bottom: 1rem; display: flex; align-items: center; gap: 1rem; flex-wrap: wrap; }
  .key-reveal .label { font-size: 0.8rem; color: var(--text-muted, #888); }
  .key-val { color: #00cc66; flex: 1; word-break: break-all; }
  .key-reveal button { background: none; border: 1px solid #00cc66; color: #00cc66;
                       padding: 0.2rem 0.6rem; cursor: pointer; font-size: 0.8rem; }
  .loading, .empty { color: var(--text-muted, #888); text-align: center; padding: 2rem; }
  .error-msg { color: #ff4444; padding: 0.5rem 0.75rem; border: 1px solid #ff4444;
               margin-bottom: 1rem; display: flex; justify-content: space-between; font-size: 0.875rem; }
  .error-msg button { background: none; border: none; color: #ff4444; cursor: pointer; }
</style>
