// frontend/src/app/(dashboard)/schedule/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { schedulesApi } from '@/lib/api';

interface Schedule {
  id: string;
  target: string;
  interval: string;
  scan_type: string;
  scan_mode: string;
  enabled: boolean;
  next_run: string | null;
  last_run: string | null;
}

export default function SchedulePage() {
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const [form, setForm] = useState({
    target: '', scan_type: 'quick', scan_mode: 'blackbox',
    target_type: 'web', interval: 'weekly', enabled: true,
  });

  async function load() {
    setLoading(true);
    try { setSchedules(await schedulesApi.list()); }
    catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  }

  useEffect(() => { load(); }, []);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!form.target.trim()) return;
    setSubmitting(true);
    try {
      await schedulesApi.create(form);
      setShowForm(false);
      setForm({ target: '', scan_type: 'quick', scan_mode: 'blackbox', target_type: 'web', interval: 'weekly', enabled: true });
      await load();
    } catch (err: any) { setError(err.message); }
    finally { setSubmitting(false); }
  }

  async function remove(id: string) { await schedulesApi.remove(id); await load(); }
  async function toggle(id: string, enabled: boolean) { await schedulesApi.toggle(id, !enabled); await load(); }

  function fmtDate(ts: string | null) {
    if (!ts) return '—';
    try { return new Date(ts).toLocaleString('nl-NL', { dateStyle: 'short', timeStyle: 'short' }); } catch { return ts; }
  }

  const inp = "bg-gray-800 border border-gray-700 text-white px-3 py-2 text-sm focus:border-cyan-400 focus:outline-none";

  return (
    <div className="p-6 max-w-5xl">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold">Geplande Scans</h1>
          <p className="text-gray-400 text-sm mt-1">{schedules.length} gepland</p>
        </div>
        <button
          onClick={() => setShowForm(v => !v)}
          className="bg-gray-800 border border-gray-700 text-white px-4 py-2 text-sm hover:border-cyan-400"
        >
          {showForm ? '✕ Annuleer' : '+ Nieuwe planning'}
        </button>
      </div>

      {showForm && (
        <form onSubmit={submit} className="bg-gray-800/50 border border-gray-700 p-5 mb-6">
          <h2 className="text-sm font-semibold mb-4">Nieuwe scan plannen</h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-3">
            <label className="flex flex-col gap-1 text-xs text-gray-400">
              Target *
              <input className={inp} value={form.target} onChange={e => setForm({ ...form, target: e.target.value })} placeholder="example.com" required />
            </label>
            <label className="flex flex-col gap-1 text-xs text-gray-400">
              Interval
              <select className={inp} value={form.interval} onChange={e => setForm({ ...form, interval: e.target.value })}>
                <option value="daily">Dagelijks</option>
                <option value="weekly">Wekelijks</option>
                <option value="monthly">Maandelijks</option>
              </select>
            </label>
            <label className="flex flex-col gap-1 text-xs text-gray-400">
              Scan type
              <select className={inp} value={form.scan_type} onChange={e => setForm({ ...form, scan_type: e.target.value })}>
                <option value="quick">Quick</option>
                <option value="full">Full</option>
              </select>
            </label>
            <label className="flex flex-col gap-1 text-xs text-gray-400">
              Modus
              <select className={inp} value={form.scan_mode} onChange={e => setForm({ ...form, scan_mode: e.target.value })}>
                <option value="blackbox">Blackbox</option>
                <option value="greybox">Greybox</option>
                <option value="whitebox">Whitebox</option>
              </select>
            </label>
          </div>
          <button type="submit" disabled={submitting || !form.target.trim()}
            className="mt-4 bg-gray-700 border border-gray-600 text-white px-5 py-2 text-sm hover:border-cyan-400 disabled:opacity-50">
            {submitting ? 'Plannen…' : 'Planning aanmaken'}
          </button>
        </form>
      )}

      {error && <div className="text-red-400 border border-red-400 p-3 mb-4 text-sm">{error}</div>}
      {loading && <div className="text-gray-400 text-center py-8">Laden…</div>}

      {!loading && schedules.length === 0 && (
        <div className="text-gray-400 text-center py-12">Geen geplande scans aangemaakt.</div>
      )}

      {!loading && schedules.length > 0 && (
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="text-left text-xs text-gray-500 uppercase tracking-wider">
              {['Target', 'Interval', 'Type / Modus', 'Volgende scan', 'Status', ''].map(h => (
                <th key={h} className="px-4 py-3 bg-gray-800/50 border-b border-gray-700">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {schedules.map(s => (
              <tr key={s.id} className={`border-b border-gray-800 ${!s.enabled ? 'opacity-50' : ''}`}>
                <td className="px-4 py-3 font-mono text-xs text-cyan-400">{s.target}</td>
                <td className="px-4 py-3">
                  <span className="bg-gray-700 text-xs px-2 py-0.5">{s.interval}</span>
                </td>
                <td className="px-4 py-3 text-gray-400">{s.scan_type} / {s.scan_mode}</td>
                <td className="px-4 py-3 text-gray-500 text-xs">{fmtDate(s.next_run)}</td>
                <td className="px-4 py-3">
                  <button onClick={() => toggle(s.id, s.enabled)}
                    className={`text-xs px-2 py-0.5 border ${s.enabled ? 'border-green-500 text-green-400' : 'border-gray-600 text-gray-500'}`}>
                    {s.enabled ? 'Actief' : 'Inactief'}
                  </button>
                </td>
                <td className="px-4 py-3">
                  <button onClick={() => remove(s.id)} className="text-gray-600 hover:text-red-400 text-sm">✕</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

// cyberpulse/frontend/src/routes/Schedule.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getSchedules, createSchedule, deleteSchedule, toggleSchedule } from '../lib/api';

  let schedules: any[] = [];
  let loading = true;
  let error = '';
  let showForm = false;

  // Form state
  let form = { target: '', scan_type: 'quick', scan_mode: 'blackbox', target_type: 'web', interval: 'weekly', enabled: true };
  let submitting = false;

  const INTERVALS = [
    { value: 'daily', label: 'Dagelijks' },
    { value: 'weekly', label: 'Wekelijks' },
    { value: 'monthly', label: 'Maandelijks' },
  ];

  onMount(async () => {
    await reload();
    loading = false;
  });

  async function reload() {
    try {
      schedules = await getSchedules();
    } catch (e: any) {
      error = e.message;
    }
  }

  async function submit() {
    if (!form.target.trim()) return;
    submitting = true;
    try {
      await createSchedule({ ...form });
      showForm = false;
      form = { target: '', scan_type: 'quick', scan_mode: 'blackbox', target_type: 'web', interval: 'weekly', enabled: true };
      await reload();
    } catch (e: any) {
      error = e.message;
    } finally {
      submitting = false;
    }
  }

  async function remove(id: string) {
    await deleteSchedule(id);
    await reload();
  }

  async function toggle(id: string, enabled: boolean) {
    await toggleSchedule(id, !enabled);
    await reload();
  }

  function formatDate(ts: string | null): string {
    if (!ts) return '—';
    try { return new Date(ts).toLocaleString('nl-NL', { dateStyle: 'short', timeStyle: 'short' }); } catch { return ts; }
  }
</script>

<div class="schedule-page">
  <header class="page-header">
    <div>
      <h1>Geplande Scans</h1>
      <p class="subtitle">{schedules.length} gepland</p>
    </div>
    <button class="btn-primary" on:click={() => showForm = !showForm}>
      {showForm ? '✕ Annuleer' : '+ Nieuwe planning'}
    </button>
  </header>

  {#if showForm}
    <div class="form-card">
      <h2>Nieuwe scan plannen</h2>
      <div class="form-grid">
        <label>
          <span>Target *</span>
          <input bind:value={form.target} placeholder="example.com / 192.168.1.0/24" />
        </label>
        <label>
          <span>Interval</span>
          <select bind:value={form.interval}>
            {#each INTERVALS as iv}
              <option value={iv.value}>{iv.label}</option>
            {/each}
          </select>
        </label>
        <label>
          <span>Scan type</span>
          <select bind:value={form.scan_type}>
            <option value="quick">Quick</option>
            <option value="full">Full</option>
            <option value="custom">Custom</option>
          </select>
        </label>
        <label>
          <span>Modus</span>
          <select bind:value={form.scan_mode}>
            <option value="blackbox">Blackbox</option>
            <option value="greybox">Greybox</option>
            <option value="whitebox">Whitebox</option>
          </select>
        </label>
        <label>
          <span>Target type</span>
          <select bind:value={form.target_type}>
            <option value="web">Web</option>
            <option value="network">Netwerk</option>
            <option value="api">API</option>
          </select>
        </label>
      </div>
      <div class="form-actions">
        <button class="btn-primary" on:click={submit} disabled={submitting || !form.target.trim()}>
          {submitting ? 'Plannen…' : 'Planning aanmaken'}
        </button>
      </div>
    </div>
  {/if}

  {#if error}
    <div class="error-msg">{error}</div>
  {/if}

  {#if loading}
    <div class="loading">Laden…</div>
  {:else if schedules.length === 0}
    <div class="empty-state">
      <p>Geen geplande scans. Maak een planning aan om automatisch te scannen.</p>
    </div>
  {:else}
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>Target</th>
            <th>Interval</th>
            <th>Type / Modus</th>
            <th>Volgende scan</th>
            <th>Laatste scan</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {#each schedules as s (s.id)}
            <tr class:disabled={!s.enabled}>
              <td class="mono">{s.target}</td>
              <td><span class="interval-badge">{s.interval}</span></td>
              <td>{s.scan_type} / {s.scan_mode}</td>
              <td class="muted">{formatDate(s.next_run)}</td>
              <td class="muted">{s.last_run ? formatDate(s.last_run) : '—'}</td>
              <td>
                <button class="toggle-btn {s.enabled ? 'active' : ''}" on:click={() => toggle(s.id, s.enabled)}>
                  {s.enabled ? 'Actief' : 'Inactief'}
                </button>
              </td>
              <td>
                <button class="icon-btn danger" on:click={() => remove(s.id)} title="Verwijderen">✕</button>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>

<style>
  .schedule-page { padding: 2rem; max-width: 1100px; }
  .page-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 1.5rem; }
  .page-header h1 { font-size: 1.5rem; font-weight: 700; margin: 0; }
  .subtitle { color: var(--text-muted, #888); font-size: 0.85rem; margin: 0.25rem 0 0; }
  .btn-primary { background: var(--accent, #1a1a1a); border: 1px solid var(--border, #444);
                 color: var(--text, #fff); padding: 0.5rem 1.25rem; cursor: pointer; font-size: 0.875rem; }
  .btn-primary:hover:not(:disabled) { border-color: var(--highlight, #0ff); }
  .btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
  .form-card { background: var(--surface, #111); border: 1px solid var(--border, #333);
               padding: 1.5rem; margin-bottom: 1.5rem; }
  .form-card h2 { font-size: 1rem; font-weight: 600; margin: 0 0 1rem; }
  .form-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem; }
  .form-grid label { display: flex; flex-direction: column; gap: 0.375rem; font-size: 0.8rem;
                     color: var(--text-muted, #888); }
  .form-grid input, .form-grid select {
    background: var(--bg, #0e0e0e); border: 1px solid var(--border, #333);
    color: var(--text, #fff); padding: 0.4rem 0.75rem; font-size: 0.875rem; outline: none;
  }
  .form-grid input:focus, .form-grid select:focus { border-color: var(--highlight, #0ff); }
  .form-actions { margin-top: 1rem; }
  .table-wrapper { overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
  th { text-align: left; padding: 0.75rem 1rem; background: var(--surface, #1a1a1a);
       border-bottom: 2px solid var(--border, #333); color: var(--text-muted, #888);
       font-weight: 600; font-size: 0.8rem; text-transform: uppercase; }
  td { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border, #222); vertical-align: middle; }
  tr.disabled td { opacity: 0.5; }
  .mono { font-family: 'JetBrains Mono', monospace; font-size: 0.8rem; }
  .muted { color: var(--text-muted, #888); font-size: 0.8rem; }
  .interval-badge { background: var(--surface, #222); border: 1px solid var(--border, #333);
                    padding: 0.15rem 0.5rem; font-size: 0.75rem; }
  .toggle-btn { padding: 0.2rem 0.6rem; font-size: 0.75rem; cursor: pointer; border: 1px solid var(--border, #444);
                background: transparent; color: var(--text-muted, #888); }
  .toggle-btn.active { border-color: #00cc66; color: #00cc66; }
  .icon-btn { background: none; border: none; cursor: pointer; color: var(--text-muted, #888); font-size: 1rem; padding: 0.25rem; }
  .icon-btn.danger:hover { color: #ff4444; }
  .loading, .empty-state { color: var(--text-muted, #888); padding: 3rem; text-align: center; }
  .error-msg { color: #ff4444; padding: 0.75rem; border: 1px solid #ff4444; margin-bottom: 1rem; font-size: 0.875rem; }
</style>
