// cyberpulse/frontend/src/routes/Notifications.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getNotifications, markNotificationRead, markAllRead, clearNotifications, getUnreadCount } from '../lib/api';

  let notifications: any[] = [];
  let loading = true;
  let error = '';
  let unreadCount = 0;

  onMount(() => reload());

  async function reload() {
    loading = true;
    try {
      [notifications, { count: unreadCount }] = await Promise.all([
        getNotifications(50),
        getUnreadCount(),
      ]);
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  async function markRead(id: string) {
    await markNotificationRead(id);
    await reload();
  }

  async function readAll() {
    await markAllRead();
    await reload();
  }

  async function clearAll() {
    if (!confirm('Alle meldingen verwijderen?')) return;
    await clearNotifications();
    await reload();
  }

  function formatTs(ts: string): string {
    try {
      const d = new Date(ts);
      const now = new Date();
      const diffMin = Math.floor((now.getTime() - d.getTime()) / 60000);
      if (diffMin < 1) return 'Zojuist';
      if (diffMin < 60) return `${diffMin} min geleden`;
      if (diffMin < 1440) return `${Math.floor(diffMin / 60)} uur geleden`;
      return d.toLocaleDateString('nl-NL');
    } catch { return ts; }
  }

  const SEV_ICONS: Record<string, string> = {
    critical: '🔴', high: '🟠', medium: '🟡', low: '🟢', info: '🔵',
  };
</script>

<div class="notif-page">
  <header class="page-header">
    <div>
      <h1>Meldingen</h1>
      {#if unreadCount > 0}
        <span class="badge">{unreadCount} ongelezen</span>
      {/if}
    </div>
    <div class="header-actions">
      {#if unreadCount > 0}
        <button class="btn-secondary" on:click={readAll}>Alles als gelezen markeren</button>
      {/if}
      {#if notifications.length > 0}
        <button class="btn-danger" on:click={clearAll}>Wis alles</button>
      {/if}
    </div>
  </header>

  {#if error}
    <div class="error-msg">{error}</div>
  {/if}

  {#if loading}
    <div class="loading">Laden…</div>
  {:else if notifications.length === 0}
    <div class="empty-state">
      <p>Geen meldingen. Meldingen verschijnen hier na een volgende scan.</p>
    </div>
  {:else}
    <div class="notif-list">
      {#each notifications as n (n.id)}
        <div class="notif-item" class:unread={!n.read} on:click={() => !n.read && markRead(n.id)} role="button" tabindex="0" on:keydown={e => e.key === 'Enter' && !n.read && markRead(n.id)}>
          <div class="notif-icon">{SEV_ICONS[n.severity] ?? '●'}</div>
          <div class="notif-body">
            <div class="notif-title">{n.title}</div>
            <div class="notif-msg">{n.message}</div>
            {#if n.scan_id}
              <div class="notif-meta">Scan: <span class="mono">{n.scan_id?.slice(0, 12)}</span></div>
            {/if}
          </div>
          <div class="notif-ts">{formatTs(n.created_at)}</div>
          {#if !n.read}
            <div class="unread-dot"></div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .notif-page { padding: 2rem; max-width: 800px; }
  .page-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 1.5rem; }
  .page-header h1 { font-size: 1.5rem; font-weight: 700; margin: 0; }
  .badge { display: inline-block; background: #ff4444; color: #fff; padding: 0.15rem 0.6rem;
           font-size: 0.75rem; font-weight: 700; margin-left: 0.5rem; vertical-align: middle; }
  .header-actions { display: flex; gap: 0.5rem; }
  .btn-secondary { background: none; border: 1px solid var(--border, #444); color: var(--text-muted, #aaa);
                   padding: 0.4rem 1rem; cursor: pointer; font-size: 0.875rem; }
  .btn-secondary:hover { border-color: var(--highlight, #0ff); color: var(--text, #fff); }
  .btn-danger { background: none; border: 1px solid #ff4444; color: #ff4444;
                padding: 0.4rem 1rem; cursor: pointer; font-size: 0.875rem; }
  .btn-danger:hover { background: rgba(255,68,68,.1); }
  .notif-list { display: flex; flex-direction: column; gap: 0; }
  .notif-item {
    display: flex; align-items: flex-start; gap: 0.75rem;
    padding: 1rem; border-bottom: 1px solid var(--border, #222);
    cursor: pointer; position: relative; transition: background 0.1s;
  }
  .notif-item:hover { background: var(--surface, #111); }
  .notif-item.unread { background: var(--surface, #0f0f1a); }
  .notif-icon { font-size: 1.2rem; flex-shrink: 0; padding-top: 0.1rem; }
  .notif-body { flex: 1; min-width: 0; }
  .notif-title { font-weight: 600; font-size: 0.9rem; margin-bottom: 0.2rem; }
  .notif-msg { font-size: 0.825rem; color: var(--text-muted, #aaa); line-height: 1.5; }
  .notif-meta { font-size: 0.75rem; color: var(--text-muted, #666); margin-top: 0.25rem; }
  .mono { font-family: monospace; }
  .notif-ts { font-size: 0.75rem; color: var(--text-muted, #666); flex-shrink: 0; white-space: nowrap; padding-top: 0.1rem; }
  .unread-dot { position: absolute; left: 0.4rem; top: 50%; transform: translateY(-50%);
                width: 6px; height: 6px; background: var(--highlight, #0ff); border-radius: 50%; }
  .loading, .empty-state { color: var(--text-muted, #888); text-align: center; padding: 3rem; }
  .error-msg { color: #ff4444; padding: 0.75rem; border: 1px solid #ff4444; margin-bottom: 1rem; font-size: 0.875rem; }
</style>

// frontend/src/app/(dashboard)/notifications/page.tsx
'use client';

import { useEffect, useState, useCallback } from 'react';
import { notificationsApi } from '@/lib/api';

const SEV_ICONS: Record<string, string> = {
  critical: '🔴', high: '🟠', medium: '🟡', low: '🟢', info: '🔵',
};

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [unread, setUnread] = useState(0);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    const [data, { count }] = await Promise.all([
      notificationsApi.list(50),
      notificationsApi.unreadCount(),
    ]);
    setNotifications(data);
    setUnread(count);
  }, []);

  useEffect(() => {
    load().finally(() => setLoading(false));
  }, [load]);

  async function markRead(id: string) {
    await notificationsApi.markRead(id);
    await load();
  }

  async function readAll() {
    await notificationsApi.markAllRead();
    await load();
  }

  async function clearAll() {
    if (!confirm('Alle meldingen verwijderen?')) return;
    await notificationsApi.clear();
    await load();
  }

  function fmtTs(ts: string) {
    try {
      const d = new Date(ts);
      const diffMin = Math.floor((Date.now() - d.getTime()) / 60000);
      if (diffMin < 1) return 'Zojuist';
      if (diffMin < 60) return `${diffMin} min geleden`;
      if (diffMin < 1440) return `${Math.floor(diffMin / 60)} uur geleden`;
      return d.toLocaleDateString('nl-NL');
    } catch { return ts; }
  }

  return (
    <div className="p-6 max-w-2xl">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-bold">Meldingen</h1>
          {unread > 0 && (
            <span className="bg-red-500 text-white text-xs font-bold px-2 py-0.5 rounded-sm">{unread}</span>
          )}
        </div>
        <div className="flex gap-2">
          {unread > 0 && (
            <button onClick={readAll} className="text-xs border border-gray-700 text-gray-400 px-3 py-1.5 hover:border-cyan-400 hover:text-white">
              Alles gelezen
            </button>
          )}
          {notifications.length > 0 && (
            <button onClick={clearAll} className="text-xs border border-red-500/50 text-red-400 px-3 py-1.5 hover:bg-red-500/10">
              Wis alles
            </button>
          )}
        </div>
      </div>

      {loading && <div className="text-gray-400 text-center py-8">Laden…</div>}

      {!loading && notifications.length === 0 && (
        <div className="text-gray-400 text-center py-12">
          Geen meldingen. Meldingen verschijnen hier na scans.
        </div>
      )}

      {!loading && notifications.length > 0 && (
        <div className="flex flex-col">
          {notifications.map(n => (
            <div
              key={n.id}
              onClick={() => !n.read && markRead(n.id)}
              className={`flex items-start gap-3 px-4 py-3.5 border-b border-gray-800 cursor-pointer transition-colors ${
                !n.read ? 'bg-gray-800/40 hover:bg-gray-800/60' : 'hover:bg-gray-800/20'
              }`}
            >
              <span className="text-xl mt-0.5 flex-shrink-0">{SEV_ICONS[n.severity] || '●'}</span>
              <div className="flex-1 min-w-0">
                <div className={`text-sm ${n.read ? 'text-gray-300' : 'text-white font-medium'}`}>{n.title}</div>
                <div className="text-xs text-gray-400 mt-0.5 leading-relaxed">{n.message}</div>
                {n.scan_id && (
                  <div className="text-xs text-gray-600 mt-1 font-mono">{n.scan_id}</div>
                )}
              </div>
              <div className="flex-shrink-0 flex items-center gap-2">
                <span className="text-xs text-gray-500 whitespace-nowrap">{fmtTs(n.created_at)}</span>
                {!n.read && <div className="w-2 h-2 bg-cyan-400 rounded-full" />}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
