// cyberpulse/frontend/src/routes/Chat.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { chatWithScan, getChatHistory, getRecentScans } from '../lib/api';

  export let scanId: string = '';

  let scans: any[] = [];
  let selectedScan = scanId;
  let messages: { role: 'user' | 'assistant'; content: string; ts?: string }[] = [];
  let input = '';
  let loading = false;
  let historyLoading = true;
  let chatContainer: HTMLElement;

  const SUGGESTED = [
    'Wat zijn de kritieke bevindingen?',
    'Hoe hoog is het risico voor mijn organisatie?',
    'Wat moet ik als eerste oplossen?',
    'Zijn er tekenen van actieve aanvallen?',
    'Leg de SQL injection bevinding uit.',
    'Geef me een herstelplan voor de high-severity problemen.',
  ];

  onMount(async () => {
    scans = await getRecentScans(30);
    if (!selectedScan && scans.length > 0) selectedScan = scans[0].scan_id;
    if (selectedScan) await loadHistory();
    historyLoading = false;
  });

  async function loadHistory() {
    if (!selectedScan) return;
    try {
      messages = await getChatHistory(selectedScan);
    } catch {
      messages = [];
    }
    scrollBottom();
  }

  async function send(text?: string) {
    const msg = (text || input).trim();
    if (!msg || !selectedScan || loading) return;
    input = '';
    messages = [...messages, { role: 'user', content: msg, ts: new Date().toISOString() }];
    loading = true;
    scrollBottom();
    try {
      const { answer } = await chatWithScan(selectedScan, msg, messages.slice(-10));
      messages = [...messages, { role: 'assistant', content: answer, ts: new Date().toISOString() }];
    } catch (e: any) {
      messages = [...messages, { role: 'assistant', content: `Fout: ${e.message}`, ts: new Date().toISOString() }];
    } finally {
      loading = false;
      scrollBottom();
    }
  }

  function scrollBottom() {
    setTimeout(() => {
      if (chatContainer) chatContainer.scrollTop = chatContainer.scrollHeight;
    }, 50);
  }

  async function changeScan() {
    messages = [];
    historyLoading = true;
    await loadHistory();
    historyLoading = false;
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  function formatTs(ts: string): string {
    try { return new Date(ts).toLocaleTimeString('nl-NL', { hour: '2-digit', minute: '2-digit' }); } catch { return ''; }
  }
</script>

<div class="chat-page">
  <header class="page-header">
    <h1>AI Pentest Assistent</h1>
    <div class="scan-select-wrap">
      <label for="scan-select">Scan:</label>
      <select id="scan-select" bind:value={selectedScan} on:change={changeScan}>
        {#each scans as s}
          <option value={s.scan_id}>{s.target} – {s.scan_type} ({s.scan_id?.slice(0, 8)})</option>
        {/each}
      </select>
    </div>
  </header>

  {#if !selectedScan}
    <div class="empty-state">Geen scan geselecteerd. Start eerst een scan.</div>
  {:else}
    <div class="chat-layout">
      <!-- Suggestions on the left -->
      <aside class="suggestions">
        <h3>Suggesties</h3>
        {#each SUGGESTED as s}
          <button class="suggestion-btn" on:click={() => send(s)}>{s}</button>
        {/each}
      </aside>

      <!-- Chat on the right -->
      <div class="chat-area">
        <div class="messages" bind:this={chatContainer}>
          {#if historyLoading}
            <div class="loading">Laden…</div>
          {:else if messages.length === 0}
            <div class="intro">
              <p>Stel een vraag over scan <strong>{selectedScan?.slice(0, 8)}</strong>.</p>
            </div>
          {:else}
            {#each messages as msg}
              <div class="message {msg.role}">
                <div class="bubble">
                  {msg.content}
                  {#if msg.ts}
                    <span class="ts">{formatTs(msg.ts)}</span>
                  {/if}
                </div>
              </div>
            {/each}
            {#if loading}
              <div class="message assistant">
                <div class="bubble thinking">
                  <span>●</span><span>●</span><span>●</span>
                </div>
              </div>
            {/if}
          {/if}
        </div>

        <div class="input-area">
          <textarea
            bind:value={input}
            on:keydown={handleKeydown}
            placeholder="Stuur een bericht… (Enter om te verzenden)"
            rows="2"
            disabled={loading}
          ></textarea>
          <button class="send-btn" on:click={() => send()} disabled={!input.trim() || loading}>
            {loading ? '…' : '→'}
          </button>
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .chat-page { padding: 2rem; height: calc(100vh - 4rem); display: flex; flex-direction: column; }
  .page-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 1.25rem; }
  .page-header h1 { font-size: 1.5rem; font-weight: 700; margin: 0; color: var(--text); }
  .scan-select-wrap { display: flex; align-items: center; gap: 0.5rem; font-size: 0.875rem; color: var(--text-2); }
  .scan-select-wrap select {
    background: var(--bg-2); border: 1px solid var(--border);
    color: var(--text); padding: 0.3rem 0.75rem; font-size: 0.875rem; max-width: 360px;
  }
  .chat-layout { display: flex; gap: 1.5rem; flex: 1; overflow: hidden; }
  .suggestions { width: 220px; flex-shrink: 0; display: flex; flex-direction: column; gap: 0.5rem; }
  .suggestions h3 { font-size: 0.8rem; text-transform: uppercase; color: var(--text-3); margin: 0 0 0.5rem; }
  .suggestion-btn {
    text-align: left; background: var(--bg-2); border: 1px solid var(--border);
    color: var(--text-2); padding: 0.5rem 0.75rem; font-size: 0.8rem; cursor: pointer; line-height: 1.4;
  }
  .suggestion-btn:hover { border-color: var(--border-2); color: var(--text); background: var(--bg-3); }
  .chat-area { flex: 1; display: flex; flex-direction: column; overflow: hidden; }
  .messages { flex: 1; overflow-y: auto; display: flex; flex-direction: column; gap: 0.75rem;
              padding: 0.5rem; background: var(--bg-3); border: 1px solid var(--border); }
  .message { display: flex; }
  .message.user { justify-content: flex-end; }
  .message.assistant { justify-content: flex-start; }
  .bubble {
    max-width: 72%; padding: 0.6rem 1rem; font-size: 0.875rem; line-height: 1.6;
    white-space: pre-wrap; word-break: break-word; position: relative; color: var(--text);
  }
  .message.user .bubble { background: var(--bg-2); border: 1px solid var(--border-2); }
  .message.assistant .bubble { background: var(--bg); border: 1px solid var(--border); }
  .ts { display: block; font-size: 0.7rem; color: var(--text-3); margin-top: 0.25rem; text-align: right; }
  .thinking span { animation: pulse 1s infinite; display: inline-block; margin-right: 2px; color: var(--text-2); }
  .thinking span:nth-child(2) { animation-delay: 0.2s; }
  .thinking span:nth-child(3) { animation-delay: 0.4s; }
  @keyframes pulse { 0%, 100% { opacity: 0.2; } 50% { opacity: 1; } }
  .input-area { display: flex; gap: 0.5rem; margin-top: 0.75rem; }
  .input-area textarea {
    flex: 1; background: var(--bg-2); border: 1px solid var(--border);
    color: var(--text); padding: 0.5rem 0.75rem; font-size: 0.875rem; resize: none; outline: none;
    font-family: inherit;
  }
  .input-area textarea:focus { border-color: var(--border-2); }
  .send-btn {
    background: var(--accent); border: 1px solid var(--accent);
    color: var(--bg); padding: 0.5rem 1.25rem; cursor: pointer; font-size: 1.1rem;
  }
  .send-btn:disabled { opacity: 0.4; cursor: not-allowed; }
  .loading, .empty-state, .intro { color: var(--text-3); text-align: center; padding: 2rem; font-size: 0.9rem; }
  .intro strong { color: var(--text); }
</style>

// frontend/src/app/(dashboard)/chat/page.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { chatApi, scansListApi } from '@/lib/api';

interface Message { role: 'user' | 'assistant'; content: string; ts: string; }

const SUGGESTED = [
  'Wat zijn de kritieke bevindingen?',
  'Hoe hoog is het risico?',
  'Wat must ik als eerste oplossen?',
  'Zijn er tekenen van actieve aanvallen?',
  'Geef een herstelplan voor high-severity problemen.',
];

export default function ChatPage() {
  const [scans, setScans] = useState<any[]>([]);
  const [selectedScan, setSelectedScan] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scansListApi.list().then(data => {
      setScans(data);
      if (data.length > 0) setSelectedScan(data[0].scan_id || data[0].id);
    }).catch(() => {});
  }, []);

  useEffect(() => {
    if (!selectedScan) return;
    chatApi.history(selectedScan).then(h => setMessages(h || [])).catch(() => setMessages([]));
  }, [selectedScan]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  async function send(text?: string) {
    const msg = (text || input).trim();
    if (!msg || !selectedScan || loading) return;
    setInput('');
    const ts = new Date().toISOString();
    setMessages(prev => [...prev, { role: 'user', content: msg, ts }]);
    setLoading(true);
    try {
      const { answer } = await chatApi.send(selectedScan, msg, messages.slice(-10));
      setMessages(prev => [...prev, { role: 'assistant', content: answer, ts: new Date().toISOString() }]);
    } catch (e: any) {
      setMessages(prev => [...prev, { role: 'assistant', content: `Fout: ${e.message}`, ts: new Date().toISOString() }]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex flex-col h-[calc(100vh-3.5rem)] p-6 max-w-5xl">
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-bold">AI Pentest Assistent</h1>
        <select
          value={selectedScan}
          onChange={e => setSelectedScan(e.target.value)}
          className="bg-gray-800 border border-gray-700 text-white px-3 py-1.5 text-sm max-w-xs"
        >
          {scans.map(s => (
            <option key={s.scan_id || s.id} value={s.scan_id || s.id}>
              {s.target} – {s.scan_type} ({(s.scan_id || s.id)?.slice(0, 8)})
            </option>
          ))}
        </select>
      </div>

      <div className="flex gap-4 flex-1 overflow-hidden">
        {/* Suggestions sidebar */}
        <aside className="w-48 flex-shrink-0 flex flex-col gap-2">
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-1">Suggesties</p>
          {SUGGESTED.map(s => (
            <button key={s} onClick={() => send(s)}
              className="text-left text-xs text-gray-400 border border-gray-700 p-2.5 hover:border-cyan-400 hover:text-white leading-relaxed">
              {s}
            </button>
          ))}
        </aside>

        {/* Chat area */}
        <div className="flex flex-col flex-1 overflow-hidden">
          <div className="flex-1 overflow-y-auto flex flex-col gap-3 p-3 bg-gray-900 border border-gray-800">
            {messages.length === 0 && !loading && (
              <div className="text-gray-500 text-sm text-center py-8">
                Stel een vraag over de geselecteerde scan.
              </div>
            )}
            {messages.map((m, i) => (
              <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[70%] px-4 py-2.5 text-sm whitespace-pre-wrap ${
                  m.role === 'user'
                    ? 'bg-gray-700 border border-gray-600'
                    : 'bg-gray-800 border border-gray-700'
                }`}>
                  {m.content}
                </div>
              </div>
            ))}
            {loading && (
              <div className="flex justify-start">
                <div className="bg-gray-800 border border-gray-700 px-4 py-2.5 text-sm text-gray-400">
                  Denken…
                </div>
              </div>
            )}
            <div ref={bottomRef} />
          </div>

          <div className="flex gap-2 mt-2">
            <textarea
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
              placeholder="Stuur een bericht… (Enter om te verzenden)"
              rows={2}
              disabled={loading}
              className="flex-1 bg-gray-800 border border-gray-700 text-white px-3 py-2 text-sm resize-none focus:border-cyan-400 focus:outline-none"
            />
            <button onClick={() => send()} disabled={!input.trim() || loading}
              className="bg-gray-700 border border-cyan-400 text-cyan-400 px-5 text-lg disabled:opacity-40">
              →
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
